[package]
name = "migrations"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros"] }
sqlx = { version = "0.7.3", features = ["postgres", "runtime-tokio-rustls"] }
dotenv = "0.15.0"
chrono = "0.4.34"
