[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "shared"
path = "src/lib.rs"

[dependencies]
sqlx = { version = "0.7.3", features = ["postgres", "runtime-tokio-rustls"] }
